/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardResearchRouteImport } from './routes/dashboard/research'
import { Route as DashboardPlannerRouteImport } from './routes/dashboard/planner'
import { Route as DashboardNotesRouteImport } from './routes/dashboard/notes'
import { Route as DashboardEmailRouteImport } from './routes/dashboard/email'
import { Route as DashboardChatRouteImport } from './routes/dashboard/chat'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResearchRoute = DashboardResearchRouteImport.update({
  id: '/dashboard/research',
  path: '/dashboard/research',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPlannerRoute = DashboardPlannerRouteImport.update({
  id: '/dashboard/planner',
  path: '/dashboard/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotesRoute = DashboardNotesRouteImport.update({
  id: '/dashboard/notes',
  path: '/dashboard/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEmailRoute = DashboardEmailRouteImport.update({
  id: '/dashboard/email',
  path: '/dashboard/email',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/dashboard/chat',
  path: '/dashboard/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/email': typeof DashboardEmailRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/research': typeof DashboardResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/email': typeof DashboardEmailRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/research': typeof DashboardResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/email': typeof DashboardEmailRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/research': typeof DashboardResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/chat'
    | '/dashboard/email'
    | '/dashboard/notes'
    | '/dashboard/planner'
    | '/dashboard/research'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/chat'
    | '/dashboard/email'
    | '/dashboard/notes'
    | '/dashboard/planner'
    | '/dashboard/research'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/chat'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/chat'
    | '/dashboard/email'
    | '/dashboard/notes'
    | '/dashboard/planner'
    | '/dashboard/research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardEmailRoute: typeof DashboardEmailRoute
  DashboardNotesRoute: typeof DashboardNotesRoute
  DashboardPlannerRoute: typeof DashboardPlannerRoute
  DashboardResearchRoute: typeof DashboardResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/research': {
      id: '/dashboard/research'
      path: '/dashboard/research'
      fullPath: '/dashboard/research'
      preLoaderRoute: typeof DashboardResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/planner': {
      id: '/dashboard/planner'
      path: '/dashboard/planner'
      fullPath: '/dashboard/planner'
      preLoaderRoute: typeof DashboardPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notes': {
      id: '/dashboard/notes'
      path: '/dashboard/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof DashboardNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/email': {
      id: '/dashboard/email'
      path: '/dashboard/email'
      fullPath: '/dashboard/email'
      preLoaderRoute: typeof DashboardEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/dashboard/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardEmailRoute: DashboardEmailRoute,
  DashboardNotesRoute: DashboardNotesRoute,
  DashboardPlannerRoute: DashboardPlannerRoute,
  DashboardResearchRoute: DashboardResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
